### ISSUE TITLE
conflicts with logicpuzzle

### ISSUE THREAD

**Issue by ZSarver** [MaPPmath/puzzlehunt.cls#1]
Documents won't compile with both the logicpuzzle package and the new puzzlehunt.cls. It complains that command \titleformat has already been defined. Very simple to reproduce: simply add \usepackage{logicpuzzle} to puzzlehunt.tex.

**Comment by StevenClontz** [comment]
This is a namespace collision between the `titlesec` [CTAN](https://www.ctan.org/pkg/titlesec) and `logicpuzzle` [CTAN](https://www.ctan.org/pkg/logicpuzzle) packages. (As an aside, there's a _reason_ I namespace all puzzlehunt.cls commands/environments as `\phCommandName`.) I haven't had such a problem before, so I'll need to do some research.

**Comment by StevenClontz** [comment]
Should be good to go now, but let me know if you hit any further issues.
